AbcBank/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "home"),
    path('auth/', include("AuthInterceptor.urls")),
    path('profile/', include("Profile.urls")),
   
]

AuthInterceptor/urls.py
from django.urls import path,include
from . import views
app_name = "AuthInterceptor"

urlpatterns = [
    path("register/", views.register, name = "signup"),
    path("login/", views.sign_in, name = "signin"),
    path("logout/", views.logout_view, name = "logout"),
]

Profile/urls.py
from . import views
from django.urls import path

app_name = "profiles"

urlpatterns = [
    path("account_status/", views.index, name = "account_status"),
    path("account_service/", views.account_service, name = "account_service"),
    path("add_fund/", views.add_fund, name = "add_fund"),
    path("statement/", views.statement, name = "statement"),
    path("manager_dashboard/", views.managerBank, name = "manager_dash"),
    path("manager_statement/", views.managerBank, name = "manager_statement"),
]

Profile/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User


class Transections(models.Model):
    source = models.ForeignKey(User, related_name='source_user', blank=True, null=True, on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name='receiver_user', blank=True, null=True, on_delete=models.CASCADE)
    amount = models.FloatField(null=True)
    created_datetime = models.DateTimeField(auto_now_add=True,null=True)
    updated_datetime = models.DateTimeField(auto_now=True,null=True) 

    def __str__(self):
        return str(self.source)

class Profile (models.Model):
    ROLE_CHOICE=[
        (0,'Customer'),
        (1,'Bank')
    ]
    account_number = models.IntegerField()
    balance = models.IntegerField()
    user = models.ForeignKey(User, related_name='satus_user', blank=True, null=True, on_delete=models.CASCADE)
    role = models.IntegerField(choices=ROLE_CHOICE,default=0)

    def __str__(self):
        return str(self.account_number)

Profile/forms.py
from django import forms
from . import models



class MoneyTransferForm (forms.ModelForm):
    class Meta:
        model = models.Transections
        fields =  "__all__"

AbcBank/views.py
from django.shortcuts import render

def index(request):
    return render(request, "index.html")

AuthInterceptor/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login
from django.contrib.auth import logout

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("AuthInterceptor:signin")
    else:
        form = UserCreationForm()
    return render(request, "accounts/create_account.html", {"form": form})

def sign_in(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("profiles:account_status")
    else:
        form = AuthenticationForm()
        return render(request, "accounts/sign_in.html", {"form": form})

def logout_view(request):
    logout(request)
    return redirect("AuthInterceptor:signin")

# Create your views here.

Profile/views.py
from django.shortcuts import render,redirect
from . import models
from .models import Profile 
from . import forms
import random
from AbcBank import utils
from django.http import HttpResponse
import csv


# Create your views here.
def randomGen():
    # return a 6 digit random number
    return int(random.uniform(100000, 999999))

def index(request):
    
    curr_user = request.user.satus_user.first()
        
    if curr_user == None:
        # if no details exist (new user), create new details
        curr_user = Profile()
        curr_user.account_number = randomGen() # random account number for every new user
        curr_user.balance = 0
        curr_user.user = request.user
        curr_user.save()
    if curr_user.role == 0 :   
        return render(request, "profiles/profile.html", {"curr_user": curr_user})
    else:
        return  redirect("profiles:manager_dash")   


def account_service(request):
    if request.method == "POST":
        
        account_number_receiver = request.POST['account_number']
        amount = request.POST['amount']
        account_receiver = Profile.objects.filter(account_number=account_number_receiver).first()
        account_receiver.balance += int(amount)
        sender_status = request.user.satus_user.all().first()
        sender_status.balance -=  int(amount)
        sender_status.save()
        account_receiver.save()
        transaction = {
            "source":request.user.id,
            "receiver":account_receiver.user.id,
            "amount":amount
        }
        form = forms.MoneyTransferForm(transaction)
        if form.is_valid():
            form.save()
            utils.SendTransactionEmail(account_receiver.user.username,amount,account_number_receiver)

        return redirect("profiles:account_status")
    else:
        return render(request, "profiles/account_service.html")

def add_fund(request):
    if request.method == "POST":
        curr_stat = request.user.satus_user.first()
        curr_stat.balance += int(request.POST['amount'])
        curr_stat.save()
        transaction = {
            "source":request.user.id,
            "receiver":request.user.id,
            "amount":request.POST['amount']
        }
        form = forms.MoneyTransferForm(transaction)
        if form.is_valid():
            form.save()
            utils.SendTransactionEmail(request.user.username,int(request.POST['amount']),curr_stat.account_number)

        return redirect("profiles:account_status")
    else:
        return render(request, "profiles/add_fund.html")

def statement(request):
    if request.method == "POST":
        curr_stat = request.user.satus_user.first()
        from_date =(request.POST['from'])+"T00:00:00"
        to_date =(request.POST['to'])+"T23:59:59"
        transactions = models.Transections.objects.filter(source=request.user,created_datetime__range=[from_date, to_date])
        print(transactions)
        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse('text/csv')
        response['Content-Disposition'] = 'attachment; filename=statement.xls'
        # Create the CSV writer using the HttpResponse as the "file"
        writer = csv.writer(response)
        writer.writerow(['id', 'From','To','Amount','Transaction Date'])
        for transaction in transactions:
            writer.writerow([transaction.id, transaction.source.email,transaction.receiver.email,transaction.amount,transaction.created_datetime])
        return response
    else:
        return render(request, "profiles/statement.html")

def managerBank(request):
    if request.method == "POST":
        ac_no =int(request.POST['ac_no'])
        curr_stat = Profile.objects.get(account_number=ac_no)
        from_date =(request.POST['from'])+"T00:00:00"
        to_date =(request.POST['to'])+"T23:59:59"
        transactions = models.Transections.objects.filter(source=curr_stat.user,created_datetime__range=[from_date, to_date])
        print(transactions)
        # Create the HttpResponse object with the appropriate CSV header.
        response = HttpResponse('text/csv')
        response['Content-Disposition'] = 'attachment; filename=statement.xls'
        # Create the CSV writer using the HttpResponse as the "file"
        writer = csv.writer(response)
        writer.writerow(['id', 'From','To','Amount','Transaction Date'])
        for transaction in transactions:
            writer.writerow([transaction.id, transaction.source.email,transaction.receiver.email,transaction.amount,transaction.created_datetime])
        return response
    else:
        return render(request, "profiles/bank.html")

AuthInterceptor/templates/accounts/create_account.html
{% extends 'base.html' %}

{% block stylecontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Slabo+27px');
        
        body {
            background-color: aliceblue;
        }
        h2 {
            font-family: 'Slabo 27px';
            border-bottom: 1px solid black;
            font-weight: 900;
        }
        form ul {
            list-style: none;
        }
    </style>

            
    <script src='https://www.google.com/recaptcha/api.js'></script>
{% endblock %}

        
{% block bodycontent %}        
    <h2 class="container text-center">Create New Account</h2>
    <h6 class="text-center"><em>(All details are mandatory)</em></h6>
    <br>
    
    <form class="container" action="{% url 'AuthInterceptor:signup' %}" method="post">
        {% csrf_token %}
        <section class="form-control">
            <h4>Enter basic details</h4>
            {{ form }}
        </section>
        <br>
        
        <!-- <div class="g-recaptcha" data-sitekey="6Ld_qjQUAAAAADjv2scrqpvXK4OrBZALRJFMANpP"></div> -->
        
        <br>
        
        <section>
            <input type="checkbox" required> 
            <small>By clicking "Create account" you agree to our  
                <a href="#">Terms and Conditions</a>.</small>
        </section>
        
        <br>
        
        <input type="submit" class="form-control btn btn-primary" value="Create account" name="submit"
        />
        
    </form>

    <br>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-create").addClass("active");

        $(".helptext").html("");

        var input_text = $("input[type=text]");
        input_text.addClass("form-control");

        var input_pass = $("input[type=password]");
        input_pass.addClass("form-control");

        $("form ul li").addClass("btn btn-danger");

        // var labels = $("label");

        // labels.addClass("col");
        // input_text.addClass("col")
        // input_pass.addClass("col");
    </script>
{% endblock %}

AuthInterceptor/templates/accounts/sign_in.html
{% extends 'base.html' %}

{% block stylecontent %}
    <style>
        body {
            background-color: aliceblue
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}


{% block bodycontent%}
        
    <div class="container"> 
        <form class="form-control" action="{% url 'AuthInterceptor:signin' %}" method="post">
            {% csrf_token %}
            <h2>Enter login details</h2>

            {{ form }}

            <br>

            <button type="submit" class="btn btn-danger">
                <i class="fa fa-sign-in"></i>
                Login
            </button>

            <br> <br>

            <small class="row">
                <a href="#" class="col text-left">Forgot password?</a>
                <a href="{% url 'AuthInterceptor:signup' %}" class="col text-right">Create New Account</a>
            </small>
        </form>
    </div>
        
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".active").removeClass("active");
        $("#nav-login").addClass("active");
        $("input").addClass("form-control");
    </script>
{% endblock %}

Profile/templates/profiles/account_service.html
{% extends 'profiles/profile_base.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}
        
{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   

        <form action="{% url 'profiles:account_service' %}" method="post">
            {% csrf_token %}

            <h3 style="font-weight: 300;">
                Account Number : <input name ="account_number" type="text"></input><br>
                Amount <input name="amount" type="number"></input><br>
            </h3>
            
            <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br>
            <button type="submit" class="btn btn-primary">Transfer amount</button>
        </form>
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

Profile/templates/profiles/add_fund.html
{% extends 'profiles/profile_base.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}
        
{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   

        <form action="{% url 'profiles:add_fund' %}" method="post">
            {% csrf_token %}

            <h3 style="font-weight: 300;">
                Voucher No : <input name ="voucher_number" type="text"></input><br>
                Amount <input name="amount" type="number"></input><br>
            </h3>
            
            <small>By transferring money from your account, you agree to the <a href="#">Terms and Conditions</a> of amount transfer</small>. <br>
            <button type="submit" class="btn btn-primary">Transfer amount</button>
        </form>
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

Profile/templates/profiles/bank.html
{% extends 'profiles/base_bank.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}
        
{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4> 
        
        <div class="text-center curr_bal"> 
            <h4>Dashboard Manager Service</h4> 
            <h1 id="curr_bal" class="btn-info">Statements</h1>
        </div>

        <form action="{% url 'profiles:manager_statement' %}" method="post">
            {% csrf_token %}

            <h3 style="font-weight: 300;"></h3>
                A/c No:  <input name="ac_no" type="number"></input><br>
                From : <input name ="from" type="date" ></input><br>
                to <input name="to" type="date"></input><br>
            </h3>
            
            <small>By generating statement from your account, you agree to the <a href="#">Terms and Conditions</a> of statemnet policy</small>. <br>
            <button type="submit" class="btn btn-primary">Get Statement</button>
        </form>
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

Profile/templates/profiles/base_bank.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Abc Bank | Profile</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        
        {% block headcontent %}
        {% endblock %}
        
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: goldenrod">
            <img src="{% static 'images/logo.png'%}" width="50px">
            <a class="navbar-brand" href="index.html">&nbsp;Abc Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'AuthInterceptor:logout' %}">Logout</a>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>
       
        <div class="container-fluid row">
        
                <!--SIDE PANEL BEGINS -->
                <section id="side_panel" class="col-3">
                    <img src="{% static 'images/logo.png'%}" class="container btn">
                    <!-- OPERATIONS -->
                    <a href="{% url 'profiles:manager_dash' %}" class="current side" id="status">Manager Daskboard</a> <br> <br>
    
                    
                </section>
                <!-- SIDE PANEL ENDS -->
        
                {% block bodycontent %}
                {% endblock %}

            </div>
       
       <!-- FOOTER -->
       <section class="foot">
        <div class="text-center">
            &copy; Website created with <i class="fa fa-heart" style="color: blue"></i> by Bhagyesh Panchal    
            <br>

        </div>
    </section>    
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>

Profile/templates/profiles/profile_base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Abc Bank | Profile</title>
        
        <!-- CSS FRAMEWORKS REQUIRED -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        
        
        {% block headcontent %}
        {% endblock %}
        
    </head>
    
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: goldenrod">
            <img src="{% static 'images/logo.png'%}" width="50px">
            <a class="navbar-brand" href="index.html">&nbsp;Abc Bank</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="{% url 'AuthInterceptor:logout' %}">Logout</a>
                </div>
            </div>
        </nav>
        
        <br> <br> <br>
       
        <div class="container-fluid row">
        
                <!--SIDE PANEL BEGINS -->
                <section id="side_panel" class="col-3">
                    <img src="{% static 'images/logo.png'%}" class="container btn">
                    <!-- OPERATIONS -->
                    <a href="{% url 'profiles:account_status' %}" class="current side" id="status">Account status</a> <br> <br>
                    <a href="{% url 'profiles:account_service' %}" class="side" id="status">Tranfer Fund</a> <br> <br>
                    <a href="{% url 'profiles:add_fund' %}" class="side" id="status">Add Fund</a> <br> <br>
                    <a href="{% url 'profiles:statement' %}" class="side" id="status">Statement</a> <br> <br>
                    
                </section>
                <!-- SIDE PANEL ENDS -->
        
                {% block bodycontent %}
                {% endblock %}

            </div>
       
       <!-- FOOTER -->
       <section class="foot">
        <div class="text-center">
            &copy; Website created with <i class="fa fa-heart" style="color: blue"></i> by Bhagyesh Panchal    
            <br>

        </div>
    </section>    
        
        <!-- JS LIBRARIES REQUIRED -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

        {% block scriptcontent %}
        {% endblock %}
    </body>
</html>

Profile/templates/profiles/statement.html
{% extends 'profiles/profile_base.html' %}

{% block headcontent %}
    <style>
        @import url('https://fonts.googleapis.com/css?family=Cinzel|PT+Serif');
        
        body {
            background-color: floralwhite;
        }
        h2 {
            font-family: "PT Serif";
        }

        #side_panel
        {
            font-size: 16px;
            font-family: "Titillium Web";
            background-color: rgb(170, 95, 57);
            margin-top: -7px;
            margin-left: -10px;
            height: 540px;
            overflow-x: auto;
            overflow-y: auto;
        }
        
        .side {
            color: aliceblue;
        }
        .side:hover {
            color: mediumaquamarine;
        }
        .warning {
            color: yellow;
        }
        .danger {
            color: #FF8723;
            font-weight: 900;
        }
        .current {
            border: 1px solid;
            padding: 3px;
        }
        .curr_bal {
            font-family: "Cinzel";
            font-weight: 600;
        }
        
        #side_panel::-webkit-scrollbar {
            width: 7px;
        }
        #side_panel::-webkit-scrollbar:hover {
            width: 12px;
        }
        #side_panel::-webkit-scrollbar-track {
            -webkit-box-shadow: inset 0 0 3px rgba(0,0,0,0.3);
            border-radius: 10px;
        }
        ::-webkit-scrollbar-thumb {
            border-radius: 10px;
            -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.5);
        }
    </style>
{% endblock %}
        
{% block bodycontent %}
    <section id="welcome_post" class="col-9">
        <h2>Welcome, <span id="prof_name">{{ user }}.</span> </h2>
        <h4 style="font-weight: 300;">It's good to have you here.</h4>   

        <form action="{% url 'profiles:statement' %}" method="post">
            {% csrf_token %}

            <h3 style="font-weight: 300;"></h3>
                From : <input name ="from" type="date" ></input><br>
                to <input name="to" type="date"></input><br>
            </h3>
            
            <small>By generating statement from your account, you agree to the <a href="#">Terms and Conditions</a> of statemnet policy</small>. <br>
            <button type="submit" class="btn btn-primary">Get Statement</button>
        </form>
    </section>
{% endblock %}

{% block scriptcontent %}
    <script>
        $(".current").removeClass("current");
        $("#transfer").addClass("current");

        $("input").addClass("form-control");
        $("label").prepend("<br>")
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block stylecontent %}
    <style>
        h1 {
            border-bottom: 1px solid;
        }
        h4 {
            font-weight: 400;
        }
        a:hover {
            text-decoration: none;
        }
        
        .foot {
            position: absolute;
            bottom: 0px;
            left: 0px;
            right: 0px;
        }
    </style>
{% endblock %}
        

{% block bodycontent %}    
    <div class="container text-center">
        <h1>Welcome to Central Bank</h1>
        <h4><em>We do not breakdown</em></h4>
    </div>
    
    <br>
    
    <div class="container">
        <a href="{% url 'AuthInterceptor:signup' %}"><button class="btn btn-warning btn-block" id="acc"><i class="fa fa-file-text"></i> Create new account</button></a>
        <br> 
        <a href="{% url 'AuthInterceptor:signin' %}"><button class="btn btn-success btn-block" id="sign_in"><i class="fa fa-sign-in"></i> Sign in</button></a>
    </div>
    
    <br>
{% endblock %}